### ISSUE TITLE
Prometheus scraping error

### ISSUE THREAD

**Issue by ochorocho** [backuppc/backuppc#403]
I'm trying to scrape metrics using Prometheus.
Each run returns `strconv.ParseFloat: parsing \"ARRAY(0x5592cb6be6f0)\": invalid syntax`

So no data is written to prometheus.

BackupPC: 4.4.0
Prometheus: version 2.7.1+ds (branch: debian/sid, revision: 2.7.1+ds-3+b11)

Prometheus scraping config

```
  - job_name: 'backuppc'
    metrics_path: "/BackupPC_Admin"
    params:
      action: ['metrics']
      format: ['prometheus']
    static_configs:
      - targets: ['127.0.0.1:80']
```

Detailed logs: 

```
level=warn ts=2020-12-20T16:33:28.201963691Z caller=scrape.go:835 component="scrape manager" scrape_pool=backuppc target="http://127.0.0.1:80/BackupPC_Admin?action=metrics&format=prometheus" msg="append failed" err="strconv.ParseFloat: parsing \"ARRAY(0x5592cb678eb8)\": invalid syntax"
level=warn ts=2020-12-20T16:33:43.201661332Z caller=scrape.go:835 component="scrape manager" scrape_pool=backuppc target="http://127.0.0.1:80/BackupPC_Admin?action=metrics&format=prometheus" msg="append failed" err="strconv.ParseFloat: parsing \"ARRAY(0x5592cb6bb430)\": invalid syntax"
level=warn ts=2020-12-20T16:33:58.196216758Z caller=scrape.go:835 component="scrape manager" scrape_pool=backuppc target="http://127.0.0.1:80/BackupPC_Admin?action=metrics&format=prometheus" msg="append failed" err="strconv.ParseFloat: parsing \"ARRAY(0x5592cb6d1f60)\": invalid syntax"
level=warn ts=2020-12-20T16:34:13.202786333Z caller=scrape.go:835 component="scrape manager" scrape_pool=backuppc target="http://127.0.0.1:80/BackupPC_Admin?action=metrics&format=prometheus" msg="append failed" err="strconv.ParseFloat: parsing \"ARRAY(0x5592cb6be6f0)\": invalid syntax"
```
